{{- if .Values.victoriametricsScrape.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ include "zen-watcher.fullname" . }}
  namespace: {{ include "zen-watcher.namespace" . }}
  labels:
    {{- include "zen-watcher.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zen-watcher.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.victoriametricsScrape.port | default "http" }}
    path: {{ .Values.victoriametricsScrape.path | default "/metrics" }}
    interval: {{ .Values.victoriametricsScrape.interval | default "30s" }}
    {{- with .Values.victoriametricsScrape.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    {{- with .Values.victoriametricsScrape.relabelConfigs }}
    relabelConfigs:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.victoriametricsScrape.metricRelabelConfigs }}
    metricRelabelConfigs:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}

